version: '3.8'

services:
  nextjs-app:
    container_name: nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '3000:3000'
    - '5555:5555'
    volumes:
    - .:/app
    - /app/node_modules # コンテナ内の node_modules をマウントしない
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
    command: npm run dev
    depends_on:
      - postgres
      - redis

    # develop:
    #   watch:
    #     # ホストマシンのカレントディレクトリをコンテナ内の /app に同期
    #     - path: .
    #       target: /app
    #       action: sync

    #     # package.jsonに変更があった場合にコンテナを再ビルドします
    #     - path: ./package.json
    #       action: rebuild

    #     # Dockerfileに変更があった場合にコンテナを再ビルドします
    #     - path: ./Dockerfile
    #       action: rebuild

    #     # next.config.mjsに変更があった場合にコンテナを再起動します
    #     - path: ./next.config.mjs
    #       action: rebuild

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:      